# Generated by Django 5.1.6 on 2025-05-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedcv',
            name='file',
            field=models.FileField(upload_to='cvs/'),
        ),
    ]
