# Generated by Django 5.1.6 on 2025-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvchat', '0002_alter_uploadedcv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcv',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadedcv',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
